name: bored
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bored_repository:
    path: packages/bored_repository
  stringx:
    path: packages/stringx
  equatable: ^1.2.5
  flutter_bloc: ^6.0.6
  auto_route: ^0.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  pedantic: ^1.9.2
  auto_route_generator: ^0.6.10

flutter:
  uses-material-design: true

