name: bored_api
description: A Dart API client for Bored API
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  json_annotation: ^3.1.0
  chopper: ^3.0.3

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.5.0
  chopper_generator: ^3.0.5

